### ISSUE TITLE
modify for Raspberry Pi 5 

### ISSUE THREAD

**Issue by Florisv1** [youfou/pianoteq-pi#7]
Are you planning to modify the script to work on the Raspberry pi 5?

**Comment by tedpower** [comment]
Yea, not sure if this is a Rasberry Pi issue or a Pianoteq trial issue, but I got this error:
```
Traceback (most recent call last):
  File "/home/tedpower/Downloads/setup.py", line 320, in <module>
    with dbm.open(CONFIG_PATH, 'c') as db:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
_dbm.error: [Errno 2] No such file or directory: '/home/pi/.config/pianoteq-pi.dbm'
```

These are the steps:
- I installed a new instance of Rasberry Pi OS 64 bit on a brand new Rasberry Pi 5
- I downlodaded the free trial here for Rasberry Pi / linux https://www.modartt.com/try
- i then ran the script, and got the above error. 

Please let me know if I'm doing something wrong

**Comment by tedpower** [comment]
OK nvm that was pretty easy — just needed to change the references from 'home/pi' to 'home/[username]' — I think usernames used to always be pi? But now I'm hitting a new error:

```
Install location (default: "/home/tedpower/"): 

Installing Pianoteq to /home/tedpower/ ...


Pianoteq 7z/zip package not found

Please download Pianoteq from Modartt website and put the 7z/zip package under the same folder.
Download: https://www.modartt.com/user_area#downloads
```

I wonder if this script somehow isn't compatible with Pianoteq 8 (vs 7)?

**Comment by erickhavel** [comment]
> OK nvm that was pretty easy — just needed to change the references from 'home/pi' to 'home/[username]' — I think usernames used to always be pi? But now I'm hitting a new error:
> 
> ```
> Install location (default: "/home/tedpower/"): 
> 
> Installing Pianoteq to /home/tedpower/ ...
> 
> 
> Pianoteq 7z/zip package not found
> 
> Please download Pianoteq from Modartt website and put the 7z/zip package under the same folder.
> Download: https://www.modartt.com/user_area#downloads
> ```
> 
> I wonder if this script somehow isn't compatible with Pianoteq 8 (vs 7)?

I'm installing on RPi 3B but had the same issue with the filename. `pianoteq_stage_linux_v820.7z` worked whereas `pianoteq_stage_linux_trial_v820.7z` didn't (the regex isn't matching for "trial").
